/**
 * KD Store - Full Curated Services Database
 * Auto-synced from provider API
 */

const SERVICES_DATA = [
  {
    "id": 574,
    "name": "متابعين تيك توك — بضمان رسمي ♻️",
    "description": "متابعين حقيقيين مع تعويض كامل وضمان رسمي في حال النقص",
    "platform": "tiktok",
    "platform_name": "تيك توك",
    "platform_en": "TikTok",
    "sub_type": "followers",
    "sub_type_name": "متابعين",
    "sub_icon": "fas fa-user-plus",
    "icon": "fab fa-tiktok",
    "color": "#fe2c55",
    "gradient": "linear-gradient(135deg, rgba(254, 44, 85, 0.25) 0%, rgba(37, 244, 238, 0.15) 100%)",
    "border_color": "#fe2c55",
    "glow": "rgba(254, 44, 85, 0.35)",
    "min": 50,
    "max": 1000000,
    "base_price_1k": 1.582,
    "has_guarantee": true,
    "guarantee": "ضمان تعويض 30 يوم ♻️",
    "guarantee_level": "medium",
    "speed": "سرعة فائقة وثبات عالي 💎"
  },
  {
    "id": 573,
    "name": "متابعين تيك توك — بدون ضمان ⚡",
    "description": "متابعين تيك توك فوريين بسعر اقتصادي مخفض وسرعة تسليم عالية",
    "platform": "tiktok",
    "platform_name": "تيك توك",
    "platform_en": "TikTok",
    "sub_type": "followers",
    "sub_type_name": "متابعين",
    "sub_icon": "fas fa-user-plus",
    "icon": "fab fa-tiktok",
    "color": "#fe2c55",
    "gradient": "linear-gradient(135deg, rgba(254, 44, 85, 0.25) 0%, rgba(37, 244, 238, 0.15) 100%)",
    "border_color": "#fe2c55",
    "glow": "rgba(254, 44, 85, 0.35)",
    "min": 50,
    "max": 1000000,
    "base_price_1k": 1.33,
    "has_guarantee": false,
    "guarantee": "بدون ضمان (اقتصادي) ⚡",
    "guarantee_level": "none",
    "speed": "تنفيذ فوري وسريع 🚀"
  },
  {
    "id": 130,
    "name": "لايكات تيك توك — بضمان رسمي ♻️",
    "description": "إعجابات حقيقية للفيديوهات مع ضمان ثبات كامل لمدة 30 يوم",
    "platform": "tiktok",
    "platform_name": "تيك توك",
    "platform_en": "TikTok",
    "sub_type": "likes",
    "sub_type_name": "لايكات",
    "sub_icon": "fas fa-heart",
    "icon": "fab fa-tiktok",
    "color": "#fe2c55",
    "gradient": "linear-gradient(135deg, rgba(254, 44, 85, 0.25) 0%, rgba(37, 244, 238, 0.15) 100%)",
    "border_color": "#fe2c55",
    "glow": "rgba(254, 44, 85, 0.35)",
    "min": 50,
    "max": 5000000,
    "base_price_1k": 0.2007,
    "has_guarantee": true,
    "guarantee": "ضمان ثبات 30 يوم ❤️",
    "guarantee_level": "medium",
    "speed": "تسليم فوري ومباشر 🚀"
  },
  {
    "id": 524,
    "name": "لايكات تيك توك — بدون ضمان ⚡",
    "description": "إعجابات فورية رخيصة جداً لرفع رواج الفيديوهات واكسبلور",
    "platform": "tiktok",
    "platform_name": "تيك توك",
    "platform_en": "TikTok",
    "sub_type": "likes",
    "sub_type_name": "لايكات",
    "sub_icon": "fas fa-heart",
    "icon": "fab fa-tiktok",
    "color": "#fe2c55",
    "gradient": "linear-gradient(135deg, rgba(254, 44, 85, 0.25) 0%, rgba(37, 244, 238, 0.15) 100%)",
    "border_color": "#fe2c55",
    "glow": "rgba(254, 44, 85, 0.35)",
    "min": 100,
    "max": 10000000,
    "base_price_1k": 0.0109,
    "has_guarantee": false,
    "guarantee": "بدون ضمان (الأرخص) ⚡",
    "guarantee_level": "none",
    "speed": "سرعة صاروخية 🔥"
  },
  {
    "id": 139,
    "name": "مشاهدات تيك توك — بضمان رسمي ♻️",
    "description": "مشاهدات فيديو وسرعة فائقة لرفع الفيديو إلى الاكسبلور بضمان 30 يوم",
    "platform": "tiktok",
    "platform_name": "تيك توك",
    "platform_en": "TikTok",
    "sub_type": "views",
    "sub_type_name": "مشاهدات",
    "sub_icon": "fas fa-eye",
    "icon": "fab fa-tiktok",
    "color": "#fe2c55",
    "gradient": "linear-gradient(135deg, rgba(254, 44, 85, 0.25) 0%, rgba(37, 244, 238, 0.15) 100%)",
    "border_color": "#fe2c55",
    "glow": "rgba(254, 44, 85, 0.35)",
    "min": 100,
    "max": 50000000,
    "base_price_1k": 0.0125,
    "has_guarantee": true,
    "guarantee": "ضمان ثبات 30 يوم ♻️",
    "guarantee_level": "medium",
    "speed": "سرعة فائقة (اكسبلور) ☄️"
  },
  {
    "id": 450,
    "name": "مشاهدات تيك توك — بدون ضمان ⚡",
    "description": "مشاهدات سريعة واقتصادية لرفع التفاعل على المقاطع فوراً",
    "platform": "tiktok",
    "platform_name": "تيك توك",
    "platform_en": "TikTok",
    "sub_type": "views",
    "sub_type_name": "مشاهدات",
    "sub_icon": "fas fa-eye",
    "icon": "fab fa-tiktok",
    "color": "#fe2c55",
    "gradient": "linear-gradient(135deg, rgba(254, 44, 85, 0.25) 0%, rgba(37, 244, 238, 0.15) 100%)",
    "border_color": "#fe2c55",
    "glow": "rgba(254, 44, 85, 0.35)",
    "min": 100,
    "max": 50000000,
    "base_price_1k": 0.0203,
    "has_guarantee": false,
    "guarantee": "بدون ضمان ⚡",
    "guarantee_level": "none",
    "speed": "فوري فائق ⚡"
  },
  {
    "id": 402,
    "name": "متابعين انستغرام — بضمان رسمي ♻️",
    "description": "متابعين بجودة عالية مع ضمان تعويض رسمي 30 يوم وسرعة تسليم ممتازة",
    "platform": "instagram",
    "platform_name": "انستغرام",
    "platform_en": "Instagram",
    "sub_type": "followers",
    "sub_type_name": "متابعين",
    "sub_icon": "fas fa-user-plus",
    "icon": "fab fa-instagram",
    "color": "#e1306c",
    "gradient": "linear-gradient(135deg, rgba(225, 48, 108, 0.25) 0%, rgba(253, 29, 29, 0.15) 50%, rgba(245, 96, 64, 0.15) 100%)",
    "border_color": "#e1306c",
    "glow": "rgba(225, 48, 108, 0.35)",
    "min": 100,
    "max": 1000000,
    "base_price_1k": 0.504,
    "has_guarantee": true,
    "guarantee": "ضمان تعويض 30 يوم ♻️",
    "guarantee_level": "medium",
    "speed": "سرعة عالية وجودة ⭐"
  },
  {
    "id": 401,
    "name": "متابعين انستغرام — بدون ضمان ⚡",
    "description": "متابعين انستغرام فوريين بسعر اقتصادي مميز",
    "platform": "instagram",
    "platform_name": "انستغرام",
    "platform_en": "Instagram",
    "sub_type": "followers",
    "sub_type_name": "متابعين",
    "sub_icon": "fas fa-user-plus",
    "icon": "fab fa-instagram",
    "color": "#e1306c",
    "gradient": "linear-gradient(135deg, rgba(225, 48, 108, 0.25) 0%, rgba(253, 29, 29, 0.15) 50%, rgba(245, 96, 64, 0.15) 100%)",
    "border_color": "#e1306c",
    "glow": "rgba(225, 48, 108, 0.35)",
    "min": 100,
    "max": 1000000,
    "base_price_1k": 0.448,
    "has_guarantee": false,
    "guarantee": "بدون ضمان ⚡",
    "guarantee_level": "none",
    "speed": "تنفيذ فوري وسريع 🚀"
  },
  {
    "id": 217,
    "name": "لايكات انستغرام — بضمان رسمي ♻️",
    "description": "إعجابات حقيقية مع ضمان ثبات مدى الحياة وسرعة فائقة",
    "platform": "instagram",
    "platform_name": "انستغرام",
    "platform_en": "Instagram",
    "sub_type": "likes",
    "sub_type_name": "لايكات",
    "sub_icon": "fas fa-heart",
    "icon": "fab fa-instagram",
    "color": "#e1306c",
    "gradient": "linear-gradient(135deg, rgba(225, 48, 108, 0.25) 0%, rgba(253, 29, 29, 0.15) 50%, rgba(245, 96, 64, 0.15) 100%)",
    "border_color": "#e1306c",
    "glow": "rgba(225, 48, 108, 0.35)",
    "min": 10,
    "max": 1000000,
    "base_price_1k": 0.0946,
    "has_guarantee": true,
    "guarantee": "ضمان مدى الحياة ♾️",
    "guarantee_level": "lifetime",
    "speed": "سريع وثابت ♥️"
  },
  {
    "id": 592,
    "name": "لايكات انستغرام — بدون ضمان ⚡",
    "description": "إعجابات رخيصة وسريعة لدعم منشوراتك وصورك فوراً",
    "platform": "instagram",
    "platform_name": "انستغرام",
    "platform_en": "Instagram",
    "sub_type": "likes",
    "sub_type_name": "لايكات",
    "sub_icon": "fas fa-heart",
    "icon": "fab fa-instagram",
    "color": "#e1306c",
    "gradient": "linear-gradient(135deg, rgba(225, 48, 108, 0.25) 0%, rgba(253, 29, 29, 0.15) 50%, rgba(245, 96, 64, 0.15) 100%)",
    "border_color": "#e1306c",
    "glow": "rgba(225, 48, 108, 0.35)",
    "min": 10,
    "max": 1000000,
    "base_price_1k": 0.0178,
    "has_guarantee": false,
    "guarantee": "بدون ضمان ⚡",
    "guarantee_level": "none",
    "speed": "فوري وسريع 🔥"
  },
  {
    "id": 542,
    "name": "مشاهدات ريلز انستغرام — بضمان رسمي ♻️",
    "description": "مشاهدات ريلز وفيديو بجودة عالية لرفع وصول الحساب والاكسبلور",
    "platform": "instagram",
    "platform_name": "انستغرام",
    "platform_en": "Instagram",
    "sub_type": "views",
    "sub_type_name": "مشاهدات",
    "sub_icon": "fas fa-eye",
    "icon": "fab fa-instagram",
    "color": "#e1306c",
    "gradient": "linear-gradient(135deg, rgba(225, 48, 108, 0.25) 0%, rgba(253, 29, 29, 0.15) 50%, rgba(245, 96, 64, 0.15) 100%)",
    "border_color": "#e1306c",
    "glow": "rgba(225, 48, 108, 0.35)",
    "min": 100,
    "max": 50000000,
    "base_price_1k": 0.0227,
    "has_guarantee": true,
    "guarantee": "ضمان ثبات رسمي ♻️",
    "guarantee_level": "medium",
    "speed": "وصول سريع اكسبلور 🚀"
  },
  {
    "id": 286,
    "name": "مشاهدات انستغرام — بدون ضمان ⚡",
    "description": "مشاهدات انستغرام الأرخص على الإطلاق للريلز والفيديوهات",
    "platform": "instagram",
    "platform_name": "انستغرام",
    "platform_en": "Instagram",
    "sub_type": "views",
    "sub_type_name": "مشاهدات",
    "sub_icon": "fas fa-eye",
    "icon": "fab fa-instagram",
    "color": "#e1306c",
    "gradient": "linear-gradient(135deg, rgba(225, 48, 108, 0.25) 0%, rgba(253, 29, 29, 0.15) 50%, rgba(245, 96, 64, 0.15) 100%)",
    "border_color": "#e1306c",
    "glow": "rgba(225, 48, 108, 0.35)",
    "min": 100,
    "max": 50000000,
    "base_price_1k": 0.0013,
    "has_guarantee": false,
    "guarantee": "بدون ضمان ⚡",
    "guarantee_level": "none",
    "speed": "فوري فائق ⚡"
  },
  {
    "id": 614,
    "name": "تعليقات انستغرام — بضمان رسمي ♻️",
    "description": "تعليقات عربية وإيجابية مخصصة لدعم منشوراتك بضمان",
    "platform": "instagram",
    "platform_name": "انستغرام",
    "platform_en": "Instagram",
    "sub_type": "comments",
    "sub_type_name": "تعليقات",
    "sub_icon": "fas fa-comment-dots",
    "icon": "fab fa-instagram",
    "color": "#e1306c",
    "gradient": "linear-gradient(135deg, rgba(225, 48, 108, 0.25) 0%, rgba(253, 29, 29, 0.15) 50%, rgba(245, 96, 64, 0.15) 100%)",
    "border_color": "#e1306c",
    "glow": "rgba(225, 48, 108, 0.35)",
    "min": 10,
    "max": 100000,
    "base_price_1k": 0.3378,
    "has_guarantee": true,
    "guarantee": "ضمان تعويض ♻️",
    "guarantee_level": "low",
    "speed": "جودة عالية وثبات ⭐"
  },
  {
    "id": 613,
    "name": "تعليقات انستغرام — بدون ضمان ⚡",
    "description": "تعليقات عشوائية سريعة واقتصادية لزيادة التفاعل",
    "platform": "instagram",
    "platform_name": "انستغرام",
    "platform_en": "Instagram",
    "sub_type": "comments",
    "sub_type_name": "تعليقات",
    "sub_icon": "fas fa-comment-dots",
    "icon": "fab fa-instagram",
    "color": "#e1306c",
    "gradient": "linear-gradient(135deg, rgba(225, 48, 108, 0.25) 0%, rgba(253, 29, 29, 0.15) 50%, rgba(245, 96, 64, 0.15) 100%)",
    "border_color": "#e1306c",
    "glow": "rgba(225, 48, 108, 0.35)",
    "min": 10,
    "max": 100000,
    "base_price_1k": 0.3191,
    "has_guarantee": false,
    "guarantee": "بدون ضمان ⚡",
    "guarantee_level": "none",
    "speed": "تسليم فوري 🚀"
  },
  {
    "id": 288,
    "name": "أعضاء قنوات تيليجرام — بضمان رسمي ♻️",
    "description": "أعضاء قنوات ومجموعات تيليجرام ثابتين بجودة عالية وضمان تعويض 30 يوم",
    "platform": "telegram",
    "platform_name": "تيليجرام",
    "platform_en": "Telegram",
    "sub_type": "followers",
    "sub_type_name": "أعضاء وقنوات",
    "sub_icon": "fas fa-user-plus",
    "icon": "fab fa-telegram-plane",
    "color": "#0088cc",
    "gradient": "linear-gradient(135deg, rgba(0, 136, 204, 0.25) 0%, rgba(34, 158, 217, 0.15) 100%)",
    "border_color": "#0088cc",
    "glow": "rgba(0, 136, 204, 0.35)",
    "min": 1,
    "max": 1000000,
    "base_price_1k": 0.2357,
    "has_guarantee": true,
    "guarantee": "ضمان تعويض 30 يوم ♻️",
    "guarantee_level": "medium",
    "speed": "ثابت وسريع 🔥"
  },
  {
    "id": 295,
    "name": "أعضاء قنوات تيليجرام — بدون ضمان ⚡",
    "description": "أعضاء تيليجرام سرعة فائقة بدون ضمان بسعر اقتصادي جداً",
    "platform": "telegram",
    "platform_name": "تيليجرام",
    "platform_en": "Telegram",
    "sub_type": "followers",
    "sub_type_name": "أعضاء وقنوات",
    "sub_icon": "fas fa-user-plus",
    "icon": "fab fa-telegram-plane",
    "color": "#0088cc",
    "gradient": "linear-gradient(135deg, rgba(0, 136, 204, 0.25) 0%, rgba(34, 158, 217, 0.15) 100%)",
    "border_color": "#0088cc",
    "glow": "rgba(0, 136, 204, 0.35)",
    "min": 1,
    "max": 1000000,
    "base_price_1k": 0.0712,
    "has_guarantee": false,
    "guarantee": "بدون ضمان ⚡",
    "guarantee_level": "none",
    "speed": "سرعة صاروخية 🚀"
  },
  {
    "id": 294,
    "name": "رشق بوتات تيليجرام — بضمان مدى الحياة 🤖",
    "description": "إضافة مستخدمين لبوتات وتطبيقات تيليجرام فوري ومدى الحياة",
    "platform": "telegram",
    "platform_name": "تيليجرام",
    "platform_en": "Telegram",
    "sub_type": "tools",
    "sub_type_name": "بوتات وأدوات",
    "sub_icon": "fas fa-robot",
    "icon": "fab fa-telegram-plane",
    "color": "#0088cc",
    "gradient": "linear-gradient(135deg, rgba(0, 136, 204, 0.25) 0%, rgba(34, 158, 217, 0.15) 100%)",
    "border_color": "#0088cc",
    "glow": "rgba(0, 136, 204, 0.35)",
    "min": 1,
    "max": 100000,
    "base_price_1k": 0.2233,
    "has_guarantee": true,
    "guarantee": "ضمان مدى الحياة ♻️",
    "guarantee_level": "lifetime",
    "speed": "سريع وثابت 🔥"
  },
  {
    "id": 364,
    "name": "متابعين فيسبوك (صفحات وبروفايل) — بضمان رسمي ♻️",
    "description": "متابعين لصفحات وحسابات فيسبوك بجودة عالية وضمان تعويض 30 يوم",
    "platform": "facebook",
    "platform_name": "فيسبوك",
    "platform_en": "Facebook",
    "sub_type": "followers",
    "sub_type_name": "متابعين",
    "sub_icon": "fas fa-user-plus",
    "icon": "fab fa-facebook-f",
    "color": "#1877f2",
    "gradient": "linear-gradient(135deg, rgba(24, 119, 242, 0.25) 0%, rgba(66, 103, 178, 0.15) 100%)",
    "border_color": "#1877f2",
    "glow": "rgba(24, 119, 242, 0.35)",
    "min": 10,
    "max": 1000000,
    "base_price_1k": 0.1654,
    "has_guarantee": true,
    "guarantee": "ضمان تعويض 30 يوم ♻️",
    "guarantee_level": "medium",
    "speed": "جودة عالية وثبات 🔥"
  },
  {
    "id": 662,
    "name": "متابعين فيسبوك (صفحات وبروفايل) — بدون ضمان ⚡",
    "description": "متابعين فيسبوك اقتصاديون بسرعة تسليم فورية",
    "platform": "facebook",
    "platform_name": "فيسبوك",
    "platform_en": "Facebook",
    "sub_type": "followers",
    "sub_type_name": "متابعين",
    "sub_icon": "fas fa-user-plus",
    "icon": "fab fa-facebook-f",
    "color": "#1877f2",
    "gradient": "linear-gradient(135deg, rgba(24, 119, 242, 0.25) 0%, rgba(66, 103, 178, 0.15) 100%)",
    "border_color": "#1877f2",
    "glow": "rgba(24, 119, 242, 0.35)",
    "min": 50,
    "max": 1000000,
    "base_price_1k": 0.0858,
    "fixed_selling_price_1k": 0.13333333333333333,
    "has_guarantee": false,
    "guarantee": "بدون ضمان ⚡",
    "guarantee_level": "none",
    "speed": "فوري وسريع 🚀"
  },
  {
    "id": 624,
    "name": "مشاهدات فيديو فيسبوك وريلز — بدون ضمان ⚡",
    "description": "مشاهدات سريعة للفيديوهات ومقاطع الريلز على فيسبوك",
    "platform": "facebook",
    "platform_name": "فيسبوك",
    "platform_en": "Facebook",
    "sub_type": "views",
    "sub_type_name": "مشاهدات",
    "sub_icon": "fas fa-eye",
    "icon": "fab fa-facebook-f",
    "color": "#1877f2",
    "gradient": "linear-gradient(135deg, rgba(24, 119, 242, 0.25) 0%, rgba(66, 103, 178, 0.15) 100%)",
    "border_color": "#1877f2",
    "glow": "rgba(24, 119, 242, 0.35)",
    "min": 100,
    "max": 100000,
    "base_price_1k": 0.0192,
    "has_guarantee": false,
    "guarantee": "بدون ضمان ⚡",
    "guarantee_level": "none",
    "speed": "فوري فائق ⚡"
  },
  {
    "id": 633,
    "name": "تفاعل لوف (Love ❤️) فيسبوك — فوري وسريع",
    "description": "تفاعل أحببته (Love ❤️) باللون الأحمر الجذاب لزيادة المحبة والتفاعل على المنشور",
    "platform": "facebook",
    "platform_name": "فيسبوك",
    "platform_en": "Facebook",
    "sub_type": "reactions",
    "sub_type_name": "تفاعلات ورياكشن",
    "sub_icon": "fas fa-heart",
    "icon": "fas fa-heart",
    "emoji": "❤️",
    "reaction_type": "لوف (Love ❤️)",
    "color": "#f43f5e",
    "gradient": "linear-gradient(135deg, rgba(244, 63, 94, 0.35) 0%, rgba(225, 29, 72, 0.2) 100%)",
    "btn_gradient": "linear-gradient(135deg, #f43f5e 0%, #e11d48 100%)",
    "border_color": "#f43f5e",
    "glow": "rgba(244, 63, 94, 0.5)",
    "min": 10,
    "max": 1000000,
    "base_price_1k": 0.0961,
    "has_guarantee": true,
    "guarantee": "وصول فوري ومضمون ❤️",
    "guarantee_level": "medium",
    "speed": "سرعة صاروخية 🔥"
  },
  {
    "id": 635,
    "name": "تفاعل واو (Wow 😲) فيسبوك — فوري وسريع",
    "description": "تفاعل أدهشني (Wow 😲) باللون الذهبي الجذاب لإبراز المنشورات المميزة",
    "platform": "facebook",
    "platform_name": "فيسبوك",
    "platform_en": "Facebook",
    "sub_type": "reactions",
    "sub_type_name": "تفاعلات ورياكشن",
    "sub_icon": "fas fa-surprise",
    "icon": "fas fa-surprise",
    "emoji": "😲",
    "reaction_type": "واو (Wow 😲)",
    "color": "#eab308",
    "gradient": "linear-gradient(135deg, rgba(234, 179, 8, 0.35) 0%, rgba(202, 138, 4, 0.2) 100%)",
    "btn_gradient": "linear-gradient(135deg, #eab308 0%, #ca8a04 100%)",
    "border_color": "#eab308",
    "glow": "rgba(234, 179, 8, 0.5)",
    "min": 10,
    "max": 1000000,
    "base_price_1k": 0.0961,
    "has_guarantee": true,
    "guarantee": "وصول فوري ومضمون 😲",
    "guarantee_level": "medium",
    "speed": "سرعة صاروخية 🔥"
  },
  {
    "id": 639,
    "name": "تفاعل أحزنني (Sad 😢) فيسبوك — فوري وسريع",
    "description": "تفاعل حزين (Sad 😢) باللون الأزرق الفاتح للمنشورات الإنسانية والخبرية",
    "platform": "facebook",
    "platform_name": "فيسبوك",
    "platform_en": "Facebook",
    "sub_type": "reactions",
    "sub_type_name": "تفاعلات ورياكشن",
    "sub_icon": "fas fa-sad-tear",
    "icon": "fas fa-sad-tear",
    "emoji": "😢",
    "reaction_type": "أحزنني (Sad 😢)",
    "color": "#38bdf8",
    "gradient": "linear-gradient(135deg, rgba(56, 189, 248, 0.35) 0%, rgba(2, 132, 199, 0.2) 100%)",
    "btn_gradient": "linear-gradient(135deg, #38bdf8 0%, #0284c7 100%)",
    "border_color": "#38bdf8",
    "glow": "rgba(56, 189, 248, 0.5)",
    "min": 10,
    "max": 1000000,
    "base_price_1k": 0.0961,
    "has_guarantee": true,
    "guarantee": "وصول فوري ومضمون 😢",
    "guarantee_level": "medium",
    "speed": "سرعة صاروخية 🔥"
  },
  {
    "id": 640,
    "name": "تفاعل ههههه (Haha 😂) فيسبوك — فوري وسريع",
    "description": "تفاعل أضحكني (Haha 😂) باللون الأصفر المبهج للمنشورات الكوميدية والترفيهية",
    "platform": "facebook",
    "platform_name": "فيسبوك",
    "platform_en": "Facebook",
    "sub_type": "reactions",
    "sub_type_name": "تفاعلات ورياكشن",
    "sub_icon": "fas fa-laugh-squint",
    "icon": "fas fa-laugh-squint",
    "emoji": "😂",
    "reaction_type": "ههههه (Haha 😂)",
    "color": "#facc15",
    "gradient": "linear-gradient(135deg, rgba(250, 204, 21, 0.35) 0%, rgba(234, 179, 8, 0.2) 100%)",
    "btn_gradient": "linear-gradient(135deg, #facc15 0%, #eab308 100%)",
    "border_color": "#facc15",
    "glow": "rgba(250, 204, 21, 0.5)",
    "min": 10,
    "max": 1000000,
    "base_price_1k": 0.0961,
    "has_guarantee": true,
    "guarantee": "وصول فوري ومضمون 😂",
    "guarantee_level": "medium",
    "speed": "سرعة صاروخية 🔥"
  },
  {
    "id": 632,
    "name": "تفاعل لايك (Like 👍) فيسبوك — فوري وسريع",
    "description": "تفاعل إعجاب كلاسيكي (Like 👍) باللون الأزرق الرسمي لفيسبوك",
    "platform": "facebook",
    "platform_name": "فيسبوك",
    "platform_en": "Facebook",
    "sub_type": "reactions",
    "sub_type_name": "تفاعلات ورياكشن",
    "sub_icon": "fas fa-thumbs-up",
    "icon": "fas fa-thumbs-up",
    "emoji": "👍",
    "reaction_type": "لايك (Like 👍)",
    "color": "#1877f2",
    "gradient": "linear-gradient(135deg, rgba(24, 119, 242, 0.35) 0%, rgba(0, 82, 204, 0.2) 100%)",
    "btn_gradient": "linear-gradient(135deg, #1877f2 0%, #0052cc 100%)",
    "border_color": "#1877f2",
    "glow": "rgba(24, 119, 242, 0.5)",
    "min": 10,
    "max": 1000000,
    "base_price_1k": 0.0961,
    "has_guarantee": true,
    "guarantee": "وصول فوري ومضمون 👍",
    "guarantee_level": "medium",
    "speed": "سرعة صاروخية 🔥"
  },
  {
    "id": 634,
    "name": "تفاعل أدعمه (Care 🤗) فيسبوك — فوري وسريع",
    "description": "تفاعل الدعم والاحتضان (Care 🤗) باللون الدافئ لزيادة التفاعل الإيجابي",
    "platform": "facebook",
    "platform_name": "فيسبوك",
    "platform_en": "Facebook",
    "sub_type": "reactions",
    "sub_type_name": "تفاعلات ورياكشن",
    "sub_icon": "fas fa-smile-beam",
    "icon": "fas fa-smile-beam",
    "emoji": "🤗",
    "reaction_type": "أدعمه (Care 🤗)",
    "color": "#f59e0b",
    "gradient": "linear-gradient(135deg, rgba(245, 158, 11, 0.35) 0%, rgba(217, 119, 6, 0.2) 100%)",
    "btn_gradient": "linear-gradient(135deg, #f59e0b 0%, #d97706 100%)",
    "border_color": "#f59e0b",
    "glow": "rgba(245, 158, 11, 0.5)",
    "min": 10,
    "max": 1000000,
    "base_price_1k": 0.0961,
    "has_guarantee": true,
    "guarantee": "وصول فوري ومضمون 🤗",
    "guarantee_level": "medium",
    "speed": "سرعة صاروخية 🔥"
  },
  {
    "id": 638,
    "name": "تفاعل أغضبني (Angry 😡) فيسبوك — فوري وسريع",
    "description": "تفاعل الغضب (Angry 😡) باللون البرتقالي الناري للمسابقات والتصويت",
    "platform": "facebook",
    "platform_name": "فيسبوك",
    "platform_en": "Facebook",
    "sub_type": "reactions",
    "sub_type_name": "تفاعلات ورياكشن",
    "sub_icon": "fas fa-angry",
    "icon": "fas fa-angry",
    "emoji": "😡",
    "reaction_type": "أغضبني (Angry 😡)",
    "color": "#ea580c",
    "gradient": "linear-gradient(135deg, rgba(234, 88, 12, 0.35) 0%, rgba(194, 65, 12, 0.2) 100%)",
    "btn_gradient": "linear-gradient(135deg, #ea580c 0%, #c2410c 100%)",
    "border_color": "#ea580c",
    "glow": "rgba(234, 88, 12, 0.5)",
    "min": 10,
    "max": 1000000,
    "base_price_1k": 0.0961,
    "has_guarantee": true,
    "guarantee": "وصول فوري ومضمون 😡",
    "guarantee_level": "medium",
    "speed": "سرعة صاروخية 🔥"
  },
  {
    "id": 617,
    "name": "مشتركين قنوات يوتيوب — بضمان رسمي ♻️",
    "description": "مشتركين حقيقيين لقنوات اليوتيوب لتفعيل شروط الأرباح بضمان رسمي",
    "platform": "youtube",
    "platform_name": "يوتيوب",
    "platform_en": "YouTube",
    "sub_type": "followers",
    "sub_type_name": "مشتركين",
    "sub_icon": "fas fa-user-plus",
    "icon": "fab fa-youtube",
    "color": "#ff0000",
    "gradient": "linear-gradient(135deg, rgba(255, 0, 0, 0.25) 0%, rgba(200, 0, 0, 0.15) 100%)",
    "border_color": "#ff0000",
    "glow": "rgba(255, 0, 0, 0.35)",
    "min": 1,
    "max": 100000,
    "base_price_1k": 0.0385,
    "has_guarantee": true,
    "guarantee": "ضمان تعويض رسمي ♻️",
    "guarantee_level": "low",
    "speed": "سريع وآمن 🚀"
  },
  {
    "id": 616,
    "name": "مشتركين قنوات يوتيوب — بدون ضمان ⚡",
    "description": "مشتركون اقتصاديون لقنوات اليوتيوب بسعر رخيص جداً",
    "platform": "youtube",
    "platform_name": "يوتيوب",
    "platform_en": "YouTube",
    "sub_type": "followers",
    "sub_type_name": "مشتركين",
    "sub_icon": "fas fa-user-plus",
    "icon": "fab fa-youtube",
    "color": "#ff0000",
    "gradient": "linear-gradient(135deg, rgba(255, 0, 0, 0.25) 0%, rgba(200, 0, 0, 0.15) 100%)",
    "border_color": "#ff0000",
    "glow": "rgba(255, 0, 0, 0.35)",
    "min": 10,
    "max": 5000,
    "base_price_1k": 0.0013,
    "has_guarantee": false,
    "guarantee": "بدون ضمان ⚡",
    "guarantee_level": "none",
    "speed": "الأرخص سعراً 🔥"
  },
  {
    "id": 270,
    "name": "لايكات يوتيوب — بضمان رسمي ♻️",
    "description": "إعجابات لفيديوهات اليوتيوب بضمان ثبات 30 يوم كاملة",
    "platform": "youtube",
    "platform_name": "يوتيوب",
    "platform_en": "YouTube",
    "sub_type": "likes",
    "sub_type_name": "لايكات",
    "sub_icon": "fas fa-heart",
    "icon": "fab fa-youtube",
    "color": "#ff0000",
    "gradient": "linear-gradient(135deg, rgba(255, 0, 0, 0.25) 0%, rgba(200, 0, 0, 0.15) 100%)",
    "border_color": "#ff0000",
    "glow": "rgba(255, 0, 0, 0.35)",
    "min": 10,
    "max": 20000,
    "base_price_1k": 0.21,
    "has_guarantee": true,
    "guarantee": "ضمان 30 يوم ❤️",
    "guarantee_level": "medium",
    "speed": "تسليم فوري ومباشر 🚀"
  },
  {
    "id": 618,
    "name": "إعجابات تعليقات يوتيوب — بضمان رسمي ♻️",
    "description": "لايكات على تعليقات اليوتيوب لتثبيتها في الأعلى بضمان 30 يوم",
    "platform": "youtube",
    "platform_name": "يوتيوب",
    "platform_en": "YouTube",
    "sub_type": "comments",
    "sub_type_name": "تعليقات",
    "sub_icon": "fas fa-comment-dots",
    "icon": "fab fa-youtube",
    "color": "#ff0000",
    "gradient": "linear-gradient(135deg, rgba(255, 0, 0, 0.25) 0%, rgba(200, 0, 0, 0.15) 100%)",
    "border_color": "#ff0000",
    "glow": "rgba(255, 0, 0, 0.35)",
    "min": 10,
    "max": 100000,
    "base_price_1k": 0.1866,
    "has_guarantee": true,
    "guarantee": "ضمان 30 يوم ♻️",
    "guarantee_level": "medium",
    "speed": "سرعة وثبات عالي 💬"
  },
  {
    "id": 603,
    "name": "أعضاء قنوات واتساب — بضمان رسمي ♻️",
    "description": "أعضاء حقيقيون لقنوات واتساب الجديدة مع ضمان ثبات 30 يوم",
    "platform": "whatsapp",
    "platform_name": "واتساب",
    "platform_en": "WhatsApp",
    "sub_type": "followers",
    "sub_type_name": "أعضاء قنوات",
    "sub_icon": "fas fa-user-plus",
    "icon": "fab fa-whatsapp",
    "color": "#25d366",
    "gradient": "linear-gradient(135deg, rgba(37, 211, 102, 0.25) 0%, rgba(18, 140, 126, 0.15) 100%)",
    "border_color": "#25d366",
    "glow": "rgba(37, 211, 102, 0.35)",
    "min": 10,
    "max": 20000,
    "base_price_1k": 0.4117,
    "has_guarantee": true,
    "guarantee": "ضمان ثبات 30 يوم ♻️",
    "guarantee_level": "medium",
    "speed": "حسابات حقيقية 🔥"
  },
  {
    "id": 602,
    "name": "أعضاء قنوات واتساب — بدون ضمان ⚡",
    "description": "أعضاء قنوات واتساب الأرخص سعراً للتكبير السريع",
    "platform": "whatsapp",
    "platform_name": "واتساب",
    "platform_en": "WhatsApp",
    "sub_type": "followers",
    "sub_type_name": "أعضاء قنوات",
    "sub_icon": "fas fa-user-plus",
    "icon": "fab fa-whatsapp",
    "color": "#25d366",
    "gradient": "linear-gradient(135deg, rgba(37, 211, 102, 0.25) 0%, rgba(18, 140, 126, 0.15) 100%)",
    "border_color": "#25d366",
    "glow": "rgba(37, 211, 102, 0.35)",
    "min": 10,
    "max": 20000,
    "base_price_1k": 0.2573,
    "has_guarantee": false,
    "guarantee": "بدون ضمان ⚡",
    "guarantee_level": "none",
    "speed": "فوري وسريع 🔥"
  },
  {
    "id": 608,
    "name": "تصويت استطلاعات واتساب 🗳️ — فوري وسريع",
    "description": "تصويت فوري على استطلاعات الرأي والمسابقات في قنوات ومجموعات واتساب",
    "platform": "whatsapp",
    "platform_name": "واتساب",
    "platform_en": "WhatsApp",
    "sub_type": "tools",
    "sub_type_name": "تصويت واستطلاعات",
    "sub_icon": "fas fa-vote-yea",
    "icon": "fab fa-whatsapp",
    "color": "#25d366",
    "gradient": "linear-gradient(135deg, rgba(37, 211, 102, 0.25) 0%, rgba(18, 140, 126, 0.15) 100%)",
    "border_color": "#25d366",
    "glow": "rgba(37, 211, 102, 0.35)",
    "min": 10,
    "max": 20000,
    "base_price_1k": 1.1578,
    "has_guarantee": true,
    "guarantee": "تنفيذ مؤكد 100% 🗳️",
    "guarantee_level": "medium",
    "speed": "تنفيذ فوري وسريع 🚀"
  },
  {
    "id": 53,
    "name": "متابعين تويتر / X — جودة عالية بضمان ♻️",
    "description": "متابعين حقيقيين لحسابات تويتر / X بجودة عالية وثبات ممتاز",
    "platform": "twitter",
    "platform_name": "تويتر / X",
    "platform_en": "Twitter / X",
    "sub_type": "followers",
    "sub_type_name": "متابعين",
    "sub_icon": "fas fa-user-plus",
    "icon": "fab fa-x-twitter",
    "color": "#1da1f2",
    "gradient": "linear-gradient(135deg, rgba(29, 161, 242, 0.25) 0%, rgba(255, 255, 255, 0.1) 100%)",
    "border_color": "#1da1f2",
    "glow": "rgba(29, 161, 242, 0.35)",
    "min": 100,
    "max": 50000,
    "base_price_1k": 2.475,
    "has_guarantee": true,
    "guarantee": "جودة عالية وثبات ⭐",
    "guarantee_level": "medium",
    "speed": "وصول سريع عالمي 🚀"
  },
  {
    "id": 54,
    "name": "متابعين تويتر / X — اقتصادي وسريع ⚡",
    "description": "متابعين حقيقيين لمنصة تويتر / X بسعر مخفض واقتصادي",
    "platform": "twitter",
    "platform_name": "تويتر / X",
    "platform_en": "Twitter / X",
    "sub_type": "followers",
    "sub_type_name": "متابعين",
    "sub_icon": "fas fa-user-plus",
    "icon": "fab fa-x-twitter",
    "color": "#1da1f2",
    "gradient": "linear-gradient(135deg, rgba(29, 161, 242, 0.25) 0%, rgba(255, 255, 255, 0.1) 100%)",
    "border_color": "#1da1f2",
    "glow": "rgba(29, 161, 242, 0.35)",
    "min": 100,
    "max": 50000,
    "base_price_1k": 1.7745,
    "has_guarantee": false,
    "guarantee": "بدون ضمان (الأرخص) ⚡",
    "guarantee_level": "none",
    "speed": "تسليم فوري ومباشر ⚡"
  },
  {
    "id": 9999,
    "name": "اشتراك Google Gemini Pro (18 شهر) — تفعيل رسمي 🤖",
    "description": "خطة 18 شهر رسمية كاملة لنموذج Gemini Pro المتطور مع تفعيل فوري",
    "platform": "ai",
    "platform_name": "اشتراكات و AI",
    "platform_en": "AI & Tools",
    "sub_type": "general",
    "sub_type_name": "اشتراكات و AI",
    "sub_icon": "fas fa-brain",
    "icon": "fas fa-robot",
    "color": "#8b5cf6",
    "gradient": "linear-gradient(135deg, rgba(139, 92, 246, 0.25) 0%, rgba(99, 102, 241, 0.2) 100%)",
    "border_color": "#8b5cf6",
    "glow": "rgba(139, 92, 246, 0.35)",
    "min": 1,
    "max": 10,
    "base_price_1k": 1500,
    "has_guarantee": true,
    "guarantee": "ضمان كامل 18 شهر ♾️",
    "guarantee_level": "lifetime",
    "speed": "تفعيل فوري خلال دقائق ⚡"
  },
  {
    "id": 285,
    "name": "مشاهدات ستوري انستغرام 👁️ — لكل القصص",
    "description": "مشاهدات سريعة وحقيقية على قصص الانستغرام (ستوري) لرفع ظهور الحساب وتفاعله",
    "platform": "instagram",
    "platform_name": "انستغرام",
    "platform_en": "Instagram",
    "sub_type": "views",
    "sub_type_name": "مشاهدات",
    "sub_icon": "fas fa-eye",
    "icon": "fab fa-instagram",
    "color": "#e1306c",
    "gradient": "linear-gradient(135deg, rgba(225, 48, 108, 0.25) 0%, rgba(253, 29, 29, 0.15) 50%, rgba(245, 96, 64, 0.15) 100%)",
    "border_color": "#e1306c",
    "glow": "rgba(225, 48, 108, 0.35)",
    "min": 10,
    "max": 15000,
    "base_price_1k": 0.1075,
    "has_guarantee": false,
    "guarantee": "مشاهدات حقيقية وسريعة 👁️",
    "guarantee_level": "low",
    "speed": "تسليم فوري ومباشر ⚡"
  },
  {
    "id": 467,
    "name": "تفاعل تيليجرام — ميكس إيجابي 👍🔥❤️🤩🎉",
    "description": "مزيج من أفضل التفاعلات الإيجابية على منشوراتك في تيليجرام مع مشاهدات مجانية",
    "platform": "telegram",
    "platform_name": "تيليجرام",
    "platform_en": "Telegram",
    "sub_type": "reactions",
    "sub_type_name": "تفاعلات ورياكشن",
    "sub_icon": "fas fa-icons",
    "icon": "fab fa-telegram-plane",
    "emoji": "🔥",
    "reaction_type": "ميكس إيجابي 🔥",
    "color": "#f97316",
    "gradient": "linear-gradient(135deg, rgba(249, 115, 22, 0.3) 0%, rgba(0, 136, 204, 0.15) 100%)",
    "btn_gradient": "linear-gradient(135deg, #f97316 0%, #ea580c 100%)",
    "border_color": "#f97316",
    "glow": "rgba(249, 115, 22, 0.5)",
    "min": 10,
    "max": 100000,
    "base_price_1k": 0.0155,
    "has_guarantee": true,
    "guarantee": "مشاهدات مجانية مع كل طلب 👁️",
    "guarantee_level": "low",
    "speed": "فوري فائق 🚀"
  },
  {
    "id": 471,
    "name": "تفاعل تيليجرام — قلب ❤️",
    "description": "تفاعل القلب الأحمر ❤️ على منشوراتك في تيليجرام مع مشاهدات مجانية",
    "platform": "telegram",
    "platform_name": "تيليجرام",
    "platform_en": "Telegram",
    "sub_type": "reactions",
    "sub_type_name": "تفاعلات ورياكشن",
    "sub_icon": "fas fa-heart",
    "icon": "fab fa-telegram-plane",
    "emoji": "❤️",
    "reaction_type": "قلب ❤️",
    "color": "#ef4444",
    "gradient": "linear-gradient(135deg, rgba(239, 68, 68, 0.3) 0%, rgba(0, 136, 204, 0.15) 100%)",
    "btn_gradient": "linear-gradient(135deg, #ef4444 0%, #dc2626 100%)",
    "border_color": "#ef4444",
    "glow": "rgba(239, 68, 68, 0.5)",
    "min": 10,
    "max": 100000,
    "base_price_1k": 0.0155,
    "has_guarantee": true,
    "guarantee": "مشاهدات مجانية مع كل طلب 👁️",
    "guarantee_level": "low",
    "speed": "فوري فائق 🚀"
  },
  {
    "id": 472,
    "name": "تفاعل تيليجرام — نار 🔥",
    "description": "تفاعل النار 🔥 الأكثر شعبية في تيليجرام لمنشوراتك مع مشاهدات مجانية",
    "platform": "telegram",
    "platform_name": "تيليجرام",
    "platform_en": "Telegram",
    "sub_type": "reactions",
    "sub_type_name": "تفاعلات ورياكشن",
    "sub_icon": "fas fa-fire",
    "icon": "fab fa-telegram-plane",
    "emoji": "🔥",
    "reaction_type": "نار 🔥",
    "color": "#fb923c",
    "gradient": "linear-gradient(135deg, rgba(251, 146, 60, 0.3) 0%, rgba(239, 68, 68, 0.15) 100%)",
    "btn_gradient": "linear-gradient(135deg, #fb923c 0%, #ea580c 100%)",
    "border_color": "#fb923c",
    "glow": "rgba(251, 146, 60, 0.5)",
    "min": 10,
    "max": 100000,
    "base_price_1k": 0.0155,
    "has_guarantee": true,
    "guarantee": "مشاهدات مجانية مع كل طلب 👁️",
    "guarantee_level": "low",
    "speed": "فوري فائق 🚀"
  },
  {
    "id": 473,
    "name": "تفاعل تيليجرام — قلب إيموجي 🥰",
    "description": "تفاعل المحبة الصادقة 🥰 لمنشوراتك وقنواتك في تيليجرام مع مشاهدات",
    "platform": "telegram",
    "platform_name": "تيليجرام",
    "platform_en": "Telegram",
    "sub_type": "reactions",
    "sub_type_name": "تفاعلات ورياكشن",
    "sub_icon": "fas fa-smile",
    "icon": "fab fa-telegram-plane",
    "emoji": "🥰",
    "reaction_type": "محبة 🥰",
    "color": "#f472b6",
    "gradient": "linear-gradient(135deg, rgba(244, 114, 182, 0.3) 0%, rgba(0, 136, 204, 0.15) 100%)",
    "btn_gradient": "linear-gradient(135deg, #f472b6 0%, #ec4899 100%)",
    "border_color": "#f472b6",
    "glow": "rgba(244, 114, 182, 0.5)",
    "min": 10,
    "max": 100000,
    "base_price_1k": 0.0155,
    "has_guarantee": true,
    "guarantee": "مشاهدات مجانية مع كل طلب 👁️",
    "guarantee_level": "low",
    "speed": "فوري فائق 🚀"
  },
  {
    "id": 482,
    "name": "تفاعل تيليجرام — احتفال 🎉",
    "description": "تفاعل الاحتفال والفرحة 🎉 لمنشوراتك ومناسباتك في تيليجرام مع مشاهدات",
    "platform": "telegram",
    "platform_name": "تيليجرام",
    "platform_en": "Telegram",
    "sub_type": "reactions",
    "sub_type_name": "تفاعلات ورياكشن",
    "sub_icon": "fas fa-star",
    "icon": "fab fa-telegram-plane",
    "emoji": "🎉",
    "reaction_type": "احتفال 🎉",
    "color": "#a78bfa",
    "gradient": "linear-gradient(135deg, rgba(167, 139, 250, 0.3) 0%, rgba(0, 136, 204, 0.15) 100%)",
    "btn_gradient": "linear-gradient(135deg, #a78bfa 0%, #7c3aed 100%)",
    "border_color": "#a78bfa",
    "glow": "rgba(167, 139, 250, 0.5)",
    "min": 10,
    "max": 100000,
    "base_price_1k": 0.0155,
    "has_guarantee": true,
    "guarantee": "مشاهدات مجانية مع كل طلب 👁️",
    "guarantee_level": "low",
    "speed": "فوري فائق 🚀"
  },
  {
    "id": 483,
    "name": "تفاعل تيليجرام — إعجاب ذهبي 🤩",
    "description": "تفاعل الانبهار والإعجاب الشديد 🤩 لتمييز أفضل منشوراتك في تيليجرام",
    "platform": "telegram",
    "platform_name": "تيليجرام",
    "platform_en": "Telegram",
    "sub_type": "reactions",
    "sub_type_name": "تفاعلات ورياكشن",
    "sub_icon": "fas fa-star",
    "icon": "fab fa-telegram-plane",
    "emoji": "🤩",
    "reaction_type": "إعجاب ذهبي 🤩",
    "color": "#fbbf24",
    "gradient": "linear-gradient(135deg, rgba(251, 191, 36, 0.3) 0%, rgba(0, 136, 204, 0.15) 100%)",
    "btn_gradient": "linear-gradient(135deg, #fbbf24 0%, #d97706 100%)",
    "border_color": "#fbbf24",
    "glow": "rgba(251, 191, 36, 0.5)",
    "min": 10,
    "max": 100000,
    "base_price_1k": 0.0155,
    "has_guarantee": true,
    "guarantee": "مشاهدات مجانية مع كل طلب 👁️",
    "guarantee_level": "low",
    "speed": "فوري فائق 🚀"
  },
  {
    "id": 469,
    "name": "تفاعل تيليجرام — إبهام 👍",
    "description": "تفاعل الإعجاب الكلاسيكي 👍 على منشوراتك في قنوات تيليجرام مع مشاهدات",
    "platform": "telegram",
    "platform_name": "تيليجرام",
    "platform_en": "Telegram",
    "sub_type": "reactions",
    "sub_type_name": "تفاعلات ورياكشن",
    "sub_icon": "fas fa-thumbs-up",
    "icon": "fab fa-telegram-plane",
    "emoji": "👍",
    "reaction_type": "إعجاب 👍",
    "color": "#0088cc",
    "gradient": "linear-gradient(135deg, rgba(0, 136, 204, 0.3) 0%, rgba(34, 158, 217, 0.15) 100%)",
    "btn_gradient": "linear-gradient(135deg, #0088cc 0%, #006fa8 100%)",
    "border_color": "#0088cc",
    "glow": "rgba(0, 136, 204, 0.5)",
    "min": 10,
    "max": 100000,
    "base_price_1k": 0.0155,
    "has_guarantee": true,
    "guarantee": "مشاهدات مجانية مع كل طلب 👁️",
    "guarantee_level": "low",
    "speed": "فوري فائق 🚀"
  },
  {
    "id": 595,
    "name": "تفاعلات واتساب — ميكس كامل 👍❤️😂😲😭🙏",
    "description": "مزيج من جميع التفاعلات المتاحة على رسائل ومنشورات قنوات واتساب",
    "platform": "whatsapp",
    "platform_name": "واتساب",
    "platform_en": "WhatsApp",
    "sub_type": "reactions",
    "sub_type_name": "تفاعلات ورياكشن",
    "sub_icon": "fas fa-icons",
    "icon": "fab fa-whatsapp",
    "emoji": "🎭",
    "reaction_type": "ميكس كامل 🎭",
    "color": "#25d366",
    "gradient": "linear-gradient(135deg, rgba(37, 211, 102, 0.3) 0%, rgba(18, 140, 126, 0.15) 100%)",
    "btn_gradient": "linear-gradient(135deg, #25d366 0%, #128c7e 100%)",
    "border_color": "#25d366",
    "glow": "rgba(37, 211, 102, 0.5)",
    "min": 10,
    "max": 20000,
    "base_price_1k": 0.0276,
    "has_guarantee": true,
    "guarantee": "مضمون 100% ✅",
    "guarantee_level": "medium",
    "speed": "سريع فوري 🚀"
  },
  {
    "id": 596,
    "name": "تفاعل واتساب — إعجاب 👍",
    "description": "تفاعل الإعجاب 👍 على رسائل ومنشورات قنوات واتساب بسرعة وضمان",
    "platform": "whatsapp",
    "platform_name": "واتساب",
    "platform_en": "WhatsApp",
    "sub_type": "reactions",
    "sub_type_name": "تفاعلات ورياكشن",
    "sub_icon": "fas fa-thumbs-up",
    "icon": "fab fa-whatsapp",
    "emoji": "👍",
    "reaction_type": "إعجاب 👍",
    "color": "#16a34a",
    "gradient": "linear-gradient(135deg, rgba(22, 163, 74, 0.3) 0%, rgba(18, 140, 126, 0.15) 100%)",
    "btn_gradient": "linear-gradient(135deg, #16a34a 0%, #15803d 100%)",
    "border_color": "#16a34a",
    "glow": "rgba(22, 163, 74, 0.5)",
    "min": 10,
    "max": 20000,
    "base_price_1k": 0.0276,
    "has_guarantee": true,
    "guarantee": "مضمون 100% ✅",
    "guarantee_level": "medium",
    "speed": "سريع فوري 🚀"
  },
  {
    "id": 597,
    "name": "تفاعل واتساب — قلب ❤️",
    "description": "تفاعل القلب والمحبة ❤️ على رسائل ومنشورات قنوات واتساب",
    "platform": "whatsapp",
    "platform_name": "واتساب",
    "platform_en": "WhatsApp",
    "sub_type": "reactions",
    "sub_type_name": "تفاعلات ورياكشن",
    "sub_icon": "fas fa-heart",
    "icon": "fab fa-whatsapp",
    "emoji": "❤️",
    "reaction_type": "قلب ❤️",
    "color": "#e11d48",
    "gradient": "linear-gradient(135deg, rgba(225, 29, 72, 0.3) 0%, rgba(18, 140, 126, 0.15) 100%)",
    "btn_gradient": "linear-gradient(135deg, #e11d48 0%, #be123c 100%)",
    "border_color": "#e11d48",
    "glow": "rgba(225, 29, 72, 0.5)",
    "min": 10,
    "max": 20000,
    "base_price_1k": 0.0276,
    "has_guarantee": true,
    "guarantee": "مضمون 100% ✅",
    "guarantee_level": "medium",
    "speed": "سريع فوري 🚀"
  },
  {
    "id": 598,
    "name": "تفاعل واتساب — ضحك 😂",
    "description": "تفاعل الضحك والفرح 😂 على رسائل ومنشورات قنوات واتساب",
    "platform": "whatsapp",
    "platform_name": "واتساب",
    "platform_en": "WhatsApp",
    "sub_type": "reactions",
    "sub_type_name": "تفاعلات ورياكشن",
    "sub_icon": "fas fa-laugh",
    "icon": "fab fa-whatsapp",
    "emoji": "😂",
    "reaction_type": "ضحك 😂",
    "color": "#ca8a04",
    "gradient": "linear-gradient(135deg, rgba(202, 138, 4, 0.3) 0%, rgba(18, 140, 126, 0.15) 100%)",
    "btn_gradient": "linear-gradient(135deg, #eab308 0%, #ca8a04 100%)",
    "border_color": "#ca8a04",
    "glow": "rgba(202, 138, 4, 0.5)",
    "min": 10,
    "max": 20000,
    "base_price_1k": 0.0276,
    "has_guarantee": true,
    "guarantee": "مضمون 100% ✅",
    "guarantee_level": "medium",
    "speed": "سريع فوري 🚀"
  },
  {
    "id": 599,
    "name": "تفاعل واتساب — دهشة 😲",
    "description": "تفاعل الدهشة والإعجاب 😲 على رسائل ومنشورات قنوات واتساب",
    "platform": "whatsapp",
    "platform_name": "واتساب",
    "platform_en": "WhatsApp",
    "sub_type": "reactions",
    "sub_type_name": "تفاعلات ورياكشن",
    "sub_icon": "fas fa-surprise",
    "icon": "fab fa-whatsapp",
    "emoji": "😲",
    "reaction_type": "دهشة 😲",
    "color": "#0369a1",
    "gradient": "linear-gradient(135deg, rgba(3, 105, 161, 0.3) 0%, rgba(18, 140, 126, 0.15) 100%)",
    "btn_gradient": "linear-gradient(135deg, #0ea5e9 0%, #0369a1 100%)",
    "border_color": "#0ea5e9",
    "glow": "rgba(14, 165, 233, 0.5)",
    "min": 10,
    "max": 20000,
    "base_price_1k": 0.0276,
    "has_guarantee": true,
    "guarantee": "مضمون 100% ✅",
    "guarantee_level": "medium",
    "speed": "سريع فوري 🚀"
  },
  {
    "id": 600,
    "name": "تفاعل واتساب — حزن 😭",
    "description": "تفاعل الحزن والتعاطف 😭 على رسائل ومنشورات قنوات واتساب",
    "platform": "whatsapp",
    "platform_name": "واتساب",
    "platform_en": "WhatsApp",
    "sub_type": "reactions",
    "sub_type_name": "تفاعلات ورياكشن",
    "sub_icon": "fas fa-sad-cry",
    "icon": "fab fa-whatsapp",
    "emoji": "😭",
    "reaction_type": "حزن 😭",
    "color": "#6366f1",
    "gradient": "linear-gradient(135deg, rgba(99, 102, 241, 0.3) 0%, rgba(18, 140, 126, 0.15) 100%)",
    "btn_gradient": "linear-gradient(135deg, #6366f1 0%, #4f46e5 100%)",
    "border_color": "#6366f1",
    "glow": "rgba(99, 102, 241, 0.5)",
    "min": 10,
    "max": 20000,
    "base_price_1k": 0.0276,
    "has_guarantee": true,
    "guarantee": "مضمون 100% ✅",
    "guarantee_level": "medium",
    "speed": "سريع فوري 🚀"
  },
  {
    "id": 601,
    "name": "تفاعل واتساب — دعاء 🙏",
    "description": "تفاعل الدعاء والامتنان 🙏 على رسائل ومنشورات قنوات واتساب",
    "platform": "whatsapp",
    "platform_name": "واتساب",
    "platform_en": "WhatsApp",
    "sub_type": "reactions",
    "sub_type_name": "تفاعلات ورياكشن",
    "sub_icon": "fas fa-praying-hands",
    "icon": "fab fa-whatsapp",
    "emoji": "🙏",
    "reaction_type": "دعاء 🙏",
    "color": "#d97706",
    "gradient": "linear-gradient(135deg, rgba(217, 119, 6, 0.3) 0%, rgba(18, 140, 126, 0.15) 100%)",
    "btn_gradient": "linear-gradient(135deg, #f59e0b 0%, #d97706 100%)",
    "border_color": "#d97706",
    "glow": "rgba(217, 119, 6, 0.5)",
    "min": 10,
    "max": 20000,
    "base_price_1k": 0.0276,
    "has_guarantee": true,
    "guarantee": "مضمون 100% ✅",
    "guarantee_level": "medium",
    "speed": "سريع فوري 🚀"
  }
];
